version: "3.8"
services:
  webapi:
    container_name: "food-api"
    image: ghcr.io/mrkresnofatih/ghcr.io/mrkresnofatih/fav-food-api:v1.0.2
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FavoriteFoodApiRedisPort=6379
      - FavoriteFoodApiRedisHost=redis
    links:
      - redisapp
    depends_on:
      - redisapp