name: Build the Application Image
on:
  push:
    branches:
      - production

jobs:
  build-push:
    name: Build Docker Image & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ghcr.io/mrkresnofatih/hi-there-you-re-cute
          registry: ghcr.io
          tags: latest, v1.0.${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}